//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int Id { get; set; }
        public int InsuranceCompanyId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string PdfFilePath { get; set; }
        public string CsvFilePath { get; set; }
        public System.DateTime GeneratedDate { get; set; }
    
        public virtual InsuranceCompanies InsuranceCompanies { get; set; }
    }
}
